version: "3.3"
services:
  jenkins-service:
    container_name: jenkins
    build: .
    privileged: true
    user: root
    ports: 
      - 84:8080
    volumes:
      - /home/debian/Formation/jenkins/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  Sonarqube-service_flask:
    container_name: sonarqube_flask
    image: sonarqube
    ports:
    - 9000:9000
