FROM jenkins/jenkins:lts
MAINTAINER ismahan
USER root
RUN apt -y update && apt -y upgrade
RUN apt-get install -y python3.10
RUN apt-get install -y pip
RUN pip install flask
RUN pip install -U pytest
RUN pip install gunicorn
