 # qui contien username et passworrd for mysql application
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque   # Opaque est le type par défaut des secrets pour des paires key-value arbitraires.
data:
  mysql-user: bXlzcWx1c2Vy    # echo -n mysqluser | base64
  mysql-password: bXlzcWxwYXNzd29yZA==   # echo -n mysqlpassword | base64
