apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data: # le contenu actuels  est le répertoire, le fichier ou la valeur littérale à partir de laquelle récupérer les données.La source de données correspond à une paire clé-valeur dans ConfigMap, où
  mysql-url: mysql-service
