FROM jenkins/jenkins:lts
MAINTAINER JPM
USER root
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt -y update && apt -y upgrade
RUN apt install -y wget build-essential libncursesw5-dev libssl-dev \libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev
RUN apt install -y make
RUN wget https://www.python.org/ftp/python/3.10.2/Python-3.10.2.tgz
RUN tar xzf Python-3.10.2.tgz
RUN cd Python-3.10.2 && ./configure --enable-optimizations && make altinstall
RUN cd ..
RUN apt install -y postgresql postgresql-contrib
RUN pip3.10 install Flask
#RUN flask run 
#RUN apt-get install -y python3.7 
#RUN apt-get install -y python3-pip 
#RUN apt-get install postgresql-10
#RUN sed -i "s/#listen_address./listen_addresses ''/" /etc/postgresql/9.5/main/postgresql.conf